"use client";
import { useExperience } from "@/components/experience-provider";

const sources = [
  { name: "Chlorophyll-a", provider: "Copernicus Marine", kind: "RECENT SATELLITE OBSERVATION", product: "OCEANCOLOUR_GLO_BGC_L3_NRT_009_101", dataset: "cmems_obs-oc_glo_bgc-plankton_nrt_l3-multi-4km_P1D_202411", variable: "CHL · milligram m-3", use: "chlUse" },
  { name: "Sea surface temperature", provider: "Copernicus Marine / OSTIA", kind: "ANALYSIS", product: "SST_GLO_SST_L4_NRT_OBSERVATIONS_010_001", dataset: "METOFFICE-GLO-SST-L4-NRT-OBS-SST-V2", variable: "analysed_sst · kelvin", use: "sstUse" },
  { name: "Waves", provider: "Copernicus Marine", kind: "FORECAST", product: "GLOBAL_ANALYSISFORECAST_WAV_001_027", dataset: "cmems_mod_glo_wav_anfc_0.083deg_PT3H-i_202411", variable: "VHM0 · m / VMDR · degree / VTPK · s", use: "waveUse" },
] as const;
export default function AboutDataPage() { const { t } = useExperience(); return <div className="page-frame data-page"><header className="page-intro"><p className="eyebrow">{t("transparency")}</p><h1>{t("dataTitle")}</h1><p>{t("dataIntro")}</p></header><section className="source-table"><div className="source-head"><span>{t("source")}</span><span>{t("verifiedDataset")}</span><span>{t("howUsed")}</span></div>{sources.map(source => <article key={source.name}><div><h2>{source.name}</h2><b>{source.provider}</b><em>{source.kind}</em></div><div><b>{source.product}</b><details><summary>{t("datasetVariables")}</summary><code>{source.dataset}<br />{source.variable}</code></details></div><p>{t(source.use)}</p></article>)}</section><section className="not-integrated"><h2>{t("readiness")}</h2><div><article><span>PFZ</span><b>{t("notIntegrated")}</b><p>{t("pfzCopy")}</p></article><article><span>{t("ecology")}</span><b>{t("integratedLocal")}</b><p>{t("ecologyCopy")}</p><p>{t("wiiCopy")}</p><p>{t("ecologyUnavailableCopy")}</p></article><article><span>{t("border")}</span><b>{t("integratedLocal")}</b><p>{t("borderCopy")}</p><p>{t("borderLimitCopy")}</p></article></div></section><section className="data-principle"><p className="eyebrow">{t("evidenceRule")}</p><blockquote>{t("missingRule")}</blockquote><p>{t("provenanceCopy")}</p><p>{t("offlineDataCopy")}</p></section></div>; }
