"use client";
import Link from "next/link";
import type { AnalysisResult, Candidate, Scorecard } from "@/lib/types";
import { SaveOfflineTripButton } from "./offline-actions";
import { useBluejury } from "./app-provider";
import { useExperience } from "./experience-provider";
import type { TranslationKey } from "@/lib/i18n";
import { evidenceCodeLabel } from "@/lib/i18n";

const statusKeys: Record<string, TranslationKey> = { "VERIFIED RESTRICTION": "verifiedRestriction", VETO: "veto", "PLACEHOLDER · NOT ASSESSED": "ecologyPlaceholderLabel", "CHECKED · INSUFFICIENT COVERAGE": "insufficientCoverage", "SOURCE UNAVAILABLE": "sourceUnavailable", CLEAR: "clear", "VERIFIED CONCERN": "verifiedConcern", "INSUFFICIENT EVIDENCE": "insufficientEvidence", "DATA UNAVAILABLE": "dataUnavailable", "AREA + ROUTE CLEAR": "areaRouteClear", "POINT + ROUTE CLEAR": "pointRouteClear", CAUTION: "caution", STRONG: "strong", MODERATE: "moderate" };
export function isEcologyPlaceholder(score: Scorecard) { return score.agent === "ecology" && !score.veto && score.confidence === 0 && (score.reason_codes.includes("PUBLIC_REFERENCE_COVERAGE_INCOMPLETE") || score.reason_codes.includes("POINT_ONLY_PROTECTED_AREA_NEARBY")); }
export function statusFor(score: Scorecard) { if (score.agent === "ecology") { if (score.veto && score.reason_codes.includes("CONFIRMED_NO_TAKE_FISHING_LOCATION")) return "VERIFIED RESTRICTION"; if (score.veto) return "VETO"; if (score.reason_codes.includes("PUBLIC_REFERENCE_COVERAGE_INCOMPLETE") || score.reason_codes.includes("POINT_ONLY_PROTECTED_AREA_NEARBY")) return "CHECKED · INSUFFICIENT COVERAGE"; if (score.reason_codes.includes("DATA_UNAVAILABLE") && !score.evidence_references.length) return "SOURCE UNAVAILABLE"; if (score.reason_codes.includes("NO_PROTECTED_AREA_INTERSECTION") && score.confidence > 0) return "CLEAR"; if (["PROTECTED_AREA_OVERLAP_RESTRICTION_UNVERIFIED", "NEAR_PROTECTED_AREA", "PROTECTED_AREA_ROUTE_TRANSIT"].some(code => score.reason_codes.includes(code))) return "VERIFIED CONCERN"; return "INSUFFICIENT EVIDENCE"; } if (score.veto) return "VETO"; if (score.confidence === 0) return "DATA UNAVAILABLE"; if (score.agent === "border") return score.score >= 70 ? (score.details?.evaluated_scope === "DESTINATION_ROUTE_AND_ACTIVITY_AREA" ? "AREA + ROUTE CLEAR" : "POINT + ROUTE CLEAR") : "CAUTION"; if (score.score >= 70) return score.agent === "catch" ? "STRONG" : "CLEAR"; return "MODERATE"; }
export function scorecard(candidate: Candidate, agent: string) { return candidate.juror_scorecards.find(item => item.agent === agent)!; }

export function Jury({ candidate }: { candidate: Candidate }) {
  const { t } = useExperience();
  const status = (card: Scorecard) => { const raw = statusFor(card); return statusKeys[raw] ? t(statusKeys[raw]) : raw; };
  return <section className="jury"><div className="section-heading"><span>{t("theJury")}</span><small>{t("independentAssessment")}</small></div>
    {candidate.juror_scorecards.map(card => { const placeholder = isEcologyPlaceholder(card); return <details key={card.agent} className={`juror ${card.veto ? "veto" : card.confidence === 0 ? "unavailable" : ""} ${placeholder ? "placeholder" : ""}`}>
      <summary><span className="juror-name">{t(card.agent)}</span><span className="juror-result">{placeholder ? <b>75</b> : card.confidence > 0 && !card.veto ? <b>{card.score}</b> : null}{!placeholder && <em>{status(card)}</em>}</span><span className="chevron">⌄</span></summary>
      <div className="juror-detail"><h4>{t("why")}</h4><p>{card.reason}</p><h4>{t("evidence")}</h4>
        {placeholder && <p className="placeholder-notice">{t("ecologyPlaceholderExplanation")}</p>}
        <p>{card.evidence_references.length ? card.evidence_references.join(" · ") : t("noEvidenceSource")}</p>
        {card.agent === "ecology" && card.details?.provider && <p>{card.details.provider} · {card.details.dataset} · {card.details.release_month}</p>}
        {card.agent === "ecology" && card.details?.coverage_note && <p>{card.details.coverage_note}</p>}
        {card.agent === "ecology" && card.details?.supplementary_ecological_context?.map(context => <div key={context.record_id} className="ecology-context"><p><strong>{t("historicalContext")}</strong></p><p>{context.site_name} · WII {context.publication_year} · {t("pointContextOnly")}</p><p className="tabular">{t("fromDestination", { value: context.destination_distance_km?.toFixed(3) ?? "—" })} · {t("fromRoute", { value: context.route_distance_km?.toFixed(3) ?? "—" })}</p><p>{context.display_notice}</p><p>{t("contextLimit")}</p></div>)}
        {card.agent === "border" && card.details?.evaluated_scope && <p>{card.details.evaluated_scope === "DESTINATION_AND_ROUTE" ? t("scopeDestinationRoute") : card.details.evaluated_scope === "DESTINATION_ROUTE_AND_ACTIVITY_AREA" ? t("scopeAreaRoute") : t("scopeAmbiguous")}</p>}
        {card.agent === "border" && card.details?.footprint_outside_km2 != null && card.details.footprint_outside_km2 > 0 && <p className="tabular">{t("footprintOutside", { area: card.details.footprint_outside_km2.toFixed(2), percent: card.details.footprint_outside_percent?.toFixed(2) ?? "—" })}</p>}
        {card.agent === "border" && card.details?.provider && <p>{card.details.provider} · {card.details.dataset} · v{card.details.version}</p>}
        <h4>{t("confidenceLabel")}</h4><p className="tabular">{Math.round(card.confidence * 100)}%{card.confidence === 0 ? card.agent === "ecology" ? ` · ${status(card)}` : ` · ${t("pending")}` : ` · ${t("deterministic")}`}</p>
      </div>
    </details>; })}
  </section>;
}

export function VetoBlock({ candidate }: { candidate: Candidate }) { const { t } = useExperience(); const veto = candidate.vetoes[0]; if (!veto) return null; const fuel = veto.agent === "fuel" ? veto.details : undefined; const available = fuel?.required_fuel_l != null && fuel.margin_l != null ? fuel.required_fuel_l + fuel.margin_l : null; return <div className="veto-block"><p className="eyebrow">{t("hardFeasibility")}</p><h2>{t(veto.agent).toUpperCase()} {t("veto")}</h2><p>{veto.reason}</p>{fuel && <div className="veto-metrics"><span>{t("available")}<strong>{available?.toFixed(1) ?? "—"} L</strong></span><span>{t("required")}<strong>{fuel.required_fuel_l?.toFixed(1)} L</strong></span><span>{t("reserveIncluded")}<strong>{t("yes")}</strong></span><span>{t("shortfall")}<strong>{Math.abs(fuel.margin_l ?? 0).toFixed(1)} L</strong></span></div>}<p className="veto-principle">{t("vetoPrinciple")}</p></div>; }

export function EvidenceList({ result }: { result: AnalysisResult }) { const { isOffline } = useBluejury(); const { t, formatDate, locale } = useExperience(); return <div className="evidence-list">{result.evidence.map(item => <article key={item.evidence_ref}><div><b>{item.variable.startsWith("CHL") ? "Chlorophyll-a" : item.variable.startsWith("analysed") ? t("sst") : t("waveHeight")}</b><span>{item.provider}</span></div><div className="evidence-meta"><strong className={isOffline || item.freshness === "CACHED" ? "cached" : ""}>{isOffline ? t("savedEvidence") : evidenceCodeLabel(locale, item.freshness)}</strong><span>{evidenceCodeLabel(locale, item.classification)}</span><span>{t("valid", { time: formatDate(item.valid_time) })}</span></div><details><summary>{t("technicalDetails")}</summary><code>{item.product_id}<br />{item.dataset_id}<br />{item.variable} · {item.unit}</code></details></article>)}</div>; }

export function DecisionPanel({ result, compact = false }: { result: AnalysisResult; compact?: boolean }) { const { t } = useExperience(); const verdict = result.verdict === "GO" ? t("go") : result.verdict === "NO_GO" ? t("noGo") : t("cautiousGo"); const winner = result.recommended_zone; if (!winner) { const candidate = result.candidates[0]; return <div className="decision-content"><p className="eyebrow">{t("verdict")}</p><h1 className="verdict no-go">{t("noGo")}</h1><p className="verdict-copy">{t("noSurvivor")}</p>{candidate && <VetoBlock candidate={candidate} />}<Options result={result} /><EvidenceList result={result} /></div>; }
  const fuel = scorecard(winner, "fuel");
  const unavailable = winner.juror_scorecards.filter(card => (card.agent === "ecology" || card.agent === "border") && card.confidence === 0);
  const coverageLimited = unavailable.some(card => card.agent === "ecology" && card.reason_codes.includes("PUBLIC_REFERENCE_COVERAGE_INCOMPLETE"));
  return <div className="decision-content"><p className="eyebrow">{t("verdict")}</p><div className="verdict-line"><h1 className={`verdict ${result.verdict === "GO" ? "go" : "cautious"}`}>{verdict}</h1><span>{t("confidence", { value: Math.round(result.overall_confidence * 100) })}</span></div><h2 className="zone-title">{winner.zone_id.replace("ZONE-", "ZONE ")}</h2><p className="verdict-copy">{winner.geometry_role === "DISCOVERY_FOOTPRINT" ? t("circlesNotCleared") : t("waitingCopy")}</p><div className="route-summary"><div><span>{t("oneWay")}</span><strong>{winner.route.distance_km.toFixed(1)} km</strong></div><div><span>{t("roundTripFuel")}</span><strong>{fuel.details?.required_fuel_l?.toFixed(1) ?? "—"} L</strong></div></div>{unavailable.length > 0 && <div className="confidence-note">{coverageLimited ? t("coverageWithhold") : `${unavailable.map(card => t(card.agent)).join(" / ")} · ${t("insufficientEvidence")}`}</div>}<Jury candidate={winner} /><section className="why"><div className="section-heading"><span>{t("whyZone", { zone: winner.zone_id.replace("ZONE-", "ZONE ") })}</span></div>{result.why_winner_won.map(reason => <p key={reason}><i>✓</i>{reason}</p>)}{unavailable.length > 0 && <p className="unavailable-reason"><i>△</i>{coverageLimited ? `${t("ecology")} · ${t("insufficientCoverage")}` : t("insufficientEvidence")}</p>}</section><Options result={result} />{!compact && <><section><div className="section-heading"><span>{t("marineEvidence")}</span><small>{result.freshness_summary}</small></div><EvidenceList result={result} /></section><SaveOfflineTripButton /><p className="method-note">{t("decisionSupportNote")} Policy {result.policy_version}.</p></>}<div className="decision-actions"><Link href="/map" className="button secondary">{t("viewMap")}</Link><Link href="/trip" className="button primary">{t("startTrip")}</Link></div></div>;
}

function Options({ result }: { result: AnalysisResult }) { const { t } = useExperience(); const others = result.candidates.filter(item => item.zone_id !== result.recommended_zone?.zone_id); return <section className="options"><div className="section-heading"><span>{t("otherOptions")}</span><small>{t("assessed", { count: others.length })}</small></div>{others.map(candidate => { const veto = candidate.vetoes[0]; return <div className="option" key={candidate.zone_id}><b>{candidate.zone_id.replace("ZONE-", "")}</b><span><strong className={veto ? "bad" : ""}>{veto ? `${t(veto.agent).toUpperCase()} ${t("veto")}` : t("feasible")}</strong><small>{candidate.route.distance_km.toFixed(1)} km · CHL {candidate.chl_percentile.toFixed(0)}th percentile</small></span></div>; })}</section>; }
