"use client";
import Link from "next/link";
import type { AnalysisResult, Candidate, Scorecard } from "@/lib/types";

const labels: Record<string, string> = { catch: "Catch", safety: "Safety", fuel: "Fuel", ecology: "Ecology", border: "Border" };
const evidenceLabel = (value: string) => value.replaceAll("_", " ");
export function statusFor(score: Scorecard) { if (score.veto) return "VETO"; if (score.confidence === 0) return "DATA UNAVAILABLE"; if (score.score >= 70) return score.agent === "catch" ? "STRONG" : "CLEAR"; return "MODERATE"; }
export function scorecard(candidate: Candidate, agent: string) { return candidate.juror_scorecards.find(item => item.agent === agent)!; }

export function Jury({ candidate }: { candidate: Candidate }) { return <section className="jury"><div className="section-heading"><span>THE JURY</span><small>Independent assessment</small></div>{candidate.juror_scorecards.map(card => <details key={card.agent} className={`juror ${card.veto ? "veto" : card.confidence === 0 ? "unavailable" : ""}`}><summary><span className="juror-name">{labels[card.agent]}</span><span className="juror-result">{card.confidence > 0 && !card.veto && <b>{card.score}</b>}<em>{statusFor(card)}</em></span><span className="chevron">⌄</span></summary><div className="juror-detail"><h4>WHY</h4><p>{card.reason}</p><h4>EVIDENCE</h4><p>{card.evidence_references.length ? `${card.evidence_references.length} verified evidence reference${card.evidence_references.length > 1 ? "s" : ""}` : "No integrated evidence source"}</p><h4>CONFIDENCE</h4><p className="tabular">{Math.round(card.confidence * 100)}%{card.confidence === 0 ? " · Evidence integration pending" : " · Deterministic policy evaluation"}</p></div></details>)}</section>; }

export function VetoBlock({ candidate }: { candidate: Candidate }) { const veto = candidate.vetoes[0]; if (!veto) return null; const fuel = veto.agent === "fuel" ? veto.details : undefined; const available = fuel?.required_fuel_l != null && fuel.margin_l != null ? fuel.required_fuel_l + fuel.margin_l : null; return <div className="veto-block"><p className="eyebrow">HARD FEASIBILITY GATE</p><h2>{veto.agent.toUpperCase()} VETO</h2><p>{veto.reason}</p>{fuel && <div className="veto-metrics"><span>Available<strong>{available?.toFixed(1) ?? "—"} L</strong></span><span>Required<strong>{fuel.required_fuel_l?.toFixed(1)} L</strong></span><span>Reserve included<strong>Yes</strong></span><span>Shortfall<strong>{Math.abs(fuel.margin_l ?? 0).toFixed(1)} L</strong></span></div>}<p className="veto-principle">High catch potential cannot override a hard feasibility constraint.</p></div>; }

export function EvidenceList({ result }: { result: AnalysisResult }) { return <div className="evidence-list">{result.evidence.map(item => <article key={item.evidence_ref}><div><b>{item.variable.startsWith("CHL") ? "Chlorophyll-a" : item.variable.startsWith("analysed") ? "Sea surface temperature" : "Significant wave height"}</b><span>{item.provider}</span></div><div className="evidence-meta"><strong className={item.freshness === "CACHED" ? "cached" : ""}>{item.freshness}</strong><span>{evidenceLabel(item.classification)}</span><span>Valid {new Date(item.valid_time).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</span></div><details><summary>Technical source details</summary><code>{item.product_id}<br />{item.dataset_id}<br />{item.variable} · {item.unit}</code></details></article>)}</div>; }

export function DecisionPanel({ result, compact = false }: { result: AnalysisResult; compact?: boolean }) { const winner = result.recommended_zone; if (!winner) { const candidate = result.candidates[0]; return <div className="decision-content"><p className="eyebrow">BLUEJURY VERDICT</p><h1 className="verdict no-go">NO-GO</h1><p className="verdict-copy">No candidate survives the current hard feasibility checks.</p>{candidate && <VetoBlock candidate={candidate} />}<Options result={result} /><EvidenceList result={result} /></div>; }
  const fuel = scorecard(winner, "fuel"); return <div className="decision-content"><p className="eyebrow">BLUEJURY VERDICT</p><div className="verdict-line"><h1 className={`verdict ${result.verdict === "GO" ? "go" : "cautious"}`}>{result.verdict.replaceAll("_", " ")}</h1><span>{Math.round(result.overall_confidence * 100)}% confidence</span></div><h2 className="zone-title">{winner.zone_id.replace("ZONE-", "ZONE ")}</h2><p className="verdict-copy">Best feasible candidate under the currently available marine and vessel evidence.</p><div className="route-summary"><div><span>ONE-WAY DISTANCE</span><strong>{winner.route.distance_km.toFixed(1)} km</strong></div><div><span>ROUND-TRIP FUEL</span><strong>{fuel.details?.required_fuel_l?.toFixed(1) ?? "—"} L</strong></div></div><div className="confidence-note">Ecology and maritime-boundary evidence are currently unavailable, so BLUEJURY withholds an unconditional GO.</div><Jury candidate={winner} /><section className="why"><div className="section-heading"><span>WHY {winner.zone_id.replace("ZONE-", "ZONE ")}?</span></div>{result.why_winner_won.map(reason => <p key={reason}><i>✓</i>{reason}</p>)}<p className="unavailable-reason"><i>△</i>Ecology and maritime-boundary evidence unavailable</p></section><Options result={result} />{!compact && <><section><div className="section-heading"><span>MARINE EVIDENCE</span><small>{result.freshness_summary}</small></div><EvidenceList result={result} /></section><p className="method-note">Decision support only—not a substitute for official warnings, seamanship or navigational charts. Policy {result.policy_version}.</p></>}<div className="decision-actions"><Link href="/map" className="button secondary">VIEW ON MAP</Link><Link href="/trip" className="button primary">START TRIP</Link></div></div>;
}

function Options({ result }: { result: AnalysisResult }) { const others = result.candidates.filter(item => item.zone_id !== result.recommended_zone?.zone_id); return <section className="options"><div className="section-heading"><span>OTHER OPTIONS</span><small>{others.length} assessed</small></div>{others.map(candidate => { const veto = candidate.vetoes[0]; return <div className="option" key={candidate.zone_id}><b>{candidate.zone_id.replace("ZONE-", "")}</b><span><strong className={veto ? "bad" : ""}>{veto ? `${veto.agent.toUpperCase()} VETO` : "FEASIBLE"}</strong><small>{candidate.route.distance_km.toFixed(1)} km · CHL {candidate.chl_percentile.toFixed(0)}th percentile</small></span></div>; })}</section>; }
