"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useBluejury } from "./app-provider";
import { statusFor } from "./decision-panel";
const MarineMap = dynamic(() => import("./marine-map").then(m => m.MarineMap), { ssr: false });
const distance = (a: [number, number], b: [number, number]) => { const r = 6371; const dLat = (b[0] - a[0]) * Math.PI / 180; const dLon = (b[1] - a[1]) * Math.PI / 180; const x = Math.sin(dLat / 2) ** 2 + Math.cos(a[0] * Math.PI / 180) * Math.cos(b[0] * Math.PI / 180) * Math.sin(dLon / 2) ** 2; return 2 * r * Math.asin(Math.sqrt(x)); };
export function LiveTrip() { const { plan, result, activeZone, runAnalysis } = useBluejury(); const [watch, setWatch] = useState<number | null>(null); const [position, setPosition] = useState<[number, number] | null>(null); const [accuracy, setAccuracy] = useState<number | null>(null); const [locationError, setLocationError] = useState(""); const [recenter, setRecenter] = useState(0); const zone = activeZone ?? result?.recommended_zone ?? null; useEffect(() => () => { if (watch != null) navigator.geolocation.clearWatch(watch); }, [watch]); const startTrip = () => { if (!navigator.geolocation) { setLocationError("LOCATION UNAVAILABLE"); return; } const id = navigator.geolocation.watchPosition(p => { setPosition([p.coords.latitude, p.coords.longitude]); setAccuracy(p.coords.accuracy); setLocationError(""); }, error => setLocationError(error.code === 1 ? "Location permission was denied. Enable location access in your browser to use Live Trip." : "LOCATION UNAVAILABLE — no GPS update could be obtained."), { enableHighAccuracy: true, maximumAge: 5000, timeout: 15000 }); setWatch(id); }; const end = () => { if (watch != null) navigator.geolocation.clearWatch(watch); setWatch(null); setPosition(null); setAccuracy(null); };
  if (!result || !zone) return <div className="empty-page"><p className="eyebrow">LIVE TRIP</p><h1>No active route.</h1><p>Complete an analysis and choose a feasible route before starting trip support.</p><Link href="/plan" className="button primary">PLAN A TRIP</Link></div>;
  const remaining = position ? distance(position, [zone.centroid.latitude, zone.centroid.longitude]) : zone.route.distance_km; return <div className="trip-workspace"><MarineMap result={result} start={plan.start} current={position} activeZone={zone} recenterKey={recenter} /><aside className="trip-panel"><div className="trip-status"><p className="eyebrow">{watch == null ? "TRIP READY" : "GPS ACTIVE"}</p><h1>ON ROUTE TO {zone.zone_id.replace("ZONE-", "ZONE ")}</h1><strong>{remaining.toFixed(1)} km <small>remaining</small></strong>{accuracy != null && <span>Position accuracy ±{Math.round(accuracy)} m</span>}</div>{locationError && <div className="location-error"><b>LOCATION UNAVAILABLE</b><p>{locationError}</p></div>}<div className="trip-jury">{zone.juror_scorecards.filter(card => card.agent !== "catch").map(card => <div key={card.agent}><span>{card.agent}</span><b className={card.veto ? "bad" : card.confidence === 0 ? "muted" : "good"}>{statusFor(card)}</b></div>)}</div><div className="freshness"><span>MARINE EVIDENCE</span><b>{result.freshness_summary}</b><small>Valid times shown in About Data and decision evidence</small></div>{watch == null ? <button className="button primary" onClick={startTrip}>START TRIP</button> : <div className="trip-controls"><button className="button secondary" onClick={() => setRecenter(v => v + 1)}>RECENTER</button><button className="button primary" onClick={() => position && runAnalysis(undefined, position)}>RE-EVALUATE</button><button className="button text-button" onClick={end}>END TRIP</button></div>}<p className="navigation-note">Decision support only. Not a substitute for navigation equipment, official warnings or seamanship.</p></aside></div>; }
