"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { useBluejury } from "./app-provider";
import { DecisionPanel, Jury, VetoBlock } from "./decision-panel";
import { LoadingSteps } from "./loading-steps";
const MarineMap = dynamic(() => import("./marine-map").then(m => m.MarineMap), { ssr: false });
export function MapWorkspace() { const search = useSearchParams(); const { plan, result, selected, setSelected, activeZone, setActiveZone, stage, error, runAnalysis } = useBluejury(); const ran = useRef(false); const [sheet, setSheet] = useState(false); const [areaResult, setAreaResult] = useState(false); useEffect(() => { if (search.get("analyze") === "1" && !ran.current) { ran.current = true; void runAnalysis(); } }, [search, runAnalysis]); const evaluate = async () => { if (selected) { const value = await runAnalysis(selected); setAreaResult(Boolean(value)); } }; const selectedCandidate = result?.candidates.find(c => c.user_selected); const selectedVeto = selectedCandidate?.vetoes[0]; const better = result && selectedCandidate && result.recommended_zone?.zone_id !== selectedCandidate.zone_id ? result.recommended_zone : null; const routeSelected = () => { if (selectedCandidate) setActiveZone(selectedCandidate); };
  return <div className="map-workspace"><MarineMap result={result} start={plan.start} selected={selected} activeZone={activeZone} onSelect={point => { setSelected(point); setAreaResult(false); }} /><aside className={`analysis-panel ${sheet ? "sheet-open" : ""}`}>{result && <button className="sheet-handle" onClick={() => setSheet(!sheet)}><span>{result.verdict.replaceAll("_", " ")} · {(activeZone ?? result.recommended_zone)?.zone_id.replace("ZONE-", "ZONE ")}</span><small>View decision {sheet ? "↓" : "↑"}</small></button>}<div className="panel-scroll">{stage !== "idle" && stage !== "done" ? <><div className="panel-title"><p className="eyebrow">BLUEJURY ANALYSIS</p><h1>Evaluating the operating area.</h1></div><LoadingSteps stage={stage} /></> : error ? <div className="failure"><p className="eyebrow">MARINE EVIDENCE UNAVAILABLE</p><h1>BLUEJURY cannot establish sufficient confidence.</h1><p>{error}</p><button className="button secondary" onClick={() => runAnalysis(selected ?? undefined)}>RETRY</button></div> : selected && (!areaResult || !selectedCandidate) ? <div className="selected-card"><p className="eyebrow">SELECTED AREA</p><h1 className="coordinates">{selected[0].toFixed(4)}° N<br />{selected[1].toFixed(4)}° E</h1><p>This point will be assessed against the same real marine evidence and hard feasibility rules.</p><button className="button primary" onClick={evaluate}>EVALUATE THIS AREA</button>{result && <button className="button text-button" onClick={() => setSelected(null)}>RETURN TO RECOMMENDATION</button>}</div> : areaResult && selectedCandidate ? <div className="area-verdict"><p className="eyebrow">BLUEJURY AREA VERDICT</p><h1 className={`verdict ${selectedVeto ? "no-go" : "cautious"}`}>{selectedVeto ? "NO-GO" : "CAUTIOUS GO"}</h1><h2>SELECTED AREA · {selectedCandidate.zone_id.replace("ZONE-", "")}</h2>{selectedVeto ? <VetoBlock candidate={selectedCandidate} /> : <><p className="verdict-copy">The selected area survives the currently integrated hard checks.</p><Jury candidate={selectedCandidate} /><button className="button primary" onClick={routeSelected}>ROUTE ME HERE</button></>}{better && <div className="better"><p>BETTER ALTERNATIVE</p><b>{better.zone_id.replace("ZONE-", "ZONE ")}</b><span>Higher negotiated score from the actual jury result.</span><button className="button secondary" onClick={() => { setActiveZone(better); setSelected(null); }}>VIEW {better.zone_id.replace("ZONE-", "ZONE ")}</button></div>}</div> : result ? <><DecisionPanel result={result} compact /><Link href="/decision/latest" className="button decision-link">VIEW FULL DECISION →</Link></> : <div className="waiting"><p className="eyebrow">MARINE ANALYSIS</p><h1>Waiting for marine evidence.</h1><p>Configure a harbour and vessel before asking BLUEJURY to evaluate fishing zones.</p><Link href="/plan" className="button primary">PLAN A TRIP</Link></div>}</div></aside></div>; }
